const sampleEvents = [
  {
    title: "National MERN Stack Hackathon",
    type: "Hackathon",
    organizer: "Coding Club IIT Delhi",
    mode: "Offline",
    location: "IIT Delhi",
    deadline: new Date("2026-03-10"),
    applyLink: "https://codingclubiitd.com/mern-hackathon",
    description: "Build full-stack applications using MERN stack in a competitive 24-hour hackathon.",
    tags: ["mern", "hackathon", "web"],
    imageURL: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Frontend Development Bootcamp",
    type: "Workshop",
    organizer: "Google Developer Student Club",
    mode: "Online",
    location: "Google Meet",
    deadline: new Date("2026-02-18"),
    applyLink: "https://gdsc.community.dev/frontend",
    description: "Learn modern frontend development using React, Tailwind, and best practices.",
    tags: ["frontend", "react", "workshop"],
    imageURL: "https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=2064&auto=format&fit=crop"
  },
  {
    title: "Backend Engineering with Node.js",
    type: "Workshop",
    organizer: "Tech Society NSUT",
    mode: "Hybrid",
    location: "NSUT / Online",
    deadline: new Date("2026-02-22"),
    applyLink: "https://techsociety.com/nodejs",
    description: "Deep dive into Node.js, Express, MongoDB, and REST API development.",
    tags: ["backend", "nodejs", "api"],
    imageURL: "https://images.unsplash.com/photo-1555099962-4199c345e5dd?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Summer Internship Drive 2026",
    type: "Internship",
    organizer: "Infosys",
    mode: "Online",
    location: "Remote",
    deadline: new Date("2026-04-05"),
    applyLink: "https://infosys.com/internships",
    description: "Apply for paid summer internships in software development and data science roles.",
    tags: ["internship", "career", "paid"],
    imageURL: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop"
  },
  {
    title: "AI & Data Science Workshop",
    type: "Workshop",
    organizer: "Analytics Club DU",
    mode: "Offline",
    location: "Delhi University",
    deadline: new Date("2026-02-25"),
    applyLink: "https://analyticsclubdu.in/ai-ds",
    description: "Hands-on AI and data science workshop with real-world datasets.",
    tags: ["ai", "data-science", "ml"],
    imageURL: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Annual Tech Fest – InnovateX",
    type: "Fest",
    organizer: "Student Council IIIT Delhi",
    mode: "Offline",
    location: "IIIT Delhi",
    deadline: new Date("2026-03-01"),
    applyLink: "https://iiitd.ac.in/innovatex",
    description: "A technology fest featuring hackathons, speaker sessions, and competitions.",
    tags: ["techfest", "innovation", "fest"],
    imageURL: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Cloud Computing with AWS",
    type: "Workshop",
    organizer: "AWS Cloud Club",
    mode: "Online",
    location: "Zoom",
    deadline: new Date("2026-02-21"),
    applyLink: "https://awsclub.com/cloud",
    description: "Learn AWS fundamentals including EC2, S3, and deployment strategies.",
    tags: ["cloud", "aws", "devops"],
    imageURL: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop"
  },
  {
    title: "Cyber Security Awareness Program",
    type: "Workshop",
    organizer: "Cyber Cell India",
    mode: "Offline",
    location: "Gurgaon",
    deadline: new Date("2026-02-27"),
    applyLink: "https://cybercellindia.org/security",
    description: "Understand cyber threats, ethical hacking basics, and online safety.",
    tags: ["cybersecurity", "ethical-hacking"],
    imageURL: "https://images.unsplash.com/photo-1510511459019-5efa36cd66cd?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Open Source Contribution Sprint",
    type: "Hackathon",
    organizer: "Mozilla Campus Club",
    mode: "Online",
    location: "GitHub",
    deadline: new Date("2026-03-08"),
    applyLink: "https://mozilla.org/opensource",
    description: "Contribute to open source projects and learn collaborative development.",
    tags: ["open-source", "github", "hackathon"],
    imageURL: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=2088&auto=format&fit=crop"
  },
  {
    title: "UI/UX Design Masterclass",
    type: "Workshop",
    organizer: "Design Studio India",
    mode: "Online",
    location: "Figma Live",
    deadline: new Date("2026-02-19"),
    applyLink: "https://designstudio.in/uiux",
    description: "Master UI/UX principles, wireframing, and prototyping using Figma.",
    tags: ["uiux", "design", "figma"],
    imageURL: "https://images.unsplash.com/photo-1561070791-2ea23f03b222?q=80&w=2000&auto=format&fit=crop"
  },
  {
    title: "Cultural Night – Rangotsav",
    type: "Fest",
    organizer: "Cultural Committee Jamia",
    mode: "Offline",
    location: "Jamia Millia Islamia",
    deadline: new Date("2026-03-03"),
    applyLink: "https://jmi.ac.in/rangotsav",
    description: "A vibrant cultural night with dance, music, and theatre performances.",
    tags: ["culture", "dance", "music"],
    imageURL: "https://images.unsplash.com/photo-1533174000220-4ee415886470?q=80&w=2069&auto=format&fit=crop"
  },
  {
    title: "Python for Beginners",
    type: "Workshop",
    organizer: "Code Academy Delhi",
    mode: "Online",
    location: "Zoom",
    deadline: new Date("2026-02-17"),
    applyLink: "https://codeacademy.in/python",
    description: "Learn Python programming from scratch with practical examples.",
    tags: ["python", "programming", "beginners"],
    imageURL: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=2000&auto=format&fit=crop"
  },
  {
    title: "Startup Pitch Competition",
    type: "Hackathon",
    organizer: "E-Cell IIT Roorkee",
    mode: "Offline",
    location: "IIT Roorkee",
    deadline: new Date("2026-03-12"),
    applyLink: "https://ecell.iitr.ac.in/pitch",
    description: "Pitch your startup idea to investors and win exciting prizes.",
    tags: ["startup", "pitch", "entrepreneurship"],
    imageURL: "https://images.unsplash.com/photo-1556761175-5973dc0f32b7?q=80&w=1932&auto=format&fit=crop"
  },
  {
    title: "Digital Marketing Internship",
    type: "Internship",
    organizer: "GrowthHackers India",
    mode: "Online",
    location: "Remote",
    deadline: new Date("2026-03-30"),
    applyLink: "https://growthhackers.in/intern",
    description: "Hands-on internship in SEO, social media marketing, and analytics.",
    tags: ["marketing", "internship", "digital"],
    imageURL: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop"
  },
  {
    title: "Competitive Programming Contest",
    type: "Hackathon",
    organizer: "CodeChef Campus Chapter",
    mode: "Online",
    location: "CodeChef",
    deadline: new Date("2026-03-06"),
    applyLink: "https://codechef.com/contest",
    description: "Test your problem-solving skills in a competitive programming contest.",
    tags: ["cp", "algorithms", "coding"],
    imageURL: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "DevOps & CI/CD Pipeline Workshop",
    type: "Workshop",
    organizer: "DevOps India Community",
    mode: "Hybrid",
    location: "Bangalore / Online",
    deadline: new Date("2026-02-24"),
    applyLink: "https://devopsindia.org/workshop",
    description: "Learn CI/CD pipelines, Docker, and deployment automation.",
    tags: ["devops", "docker", "ci-cd"],
    imageURL: "https://images.unsplash.com/photo-1618401479427-c8ef9465fbe1?q=80&w=2043&auto=format&fit=crop"
  },
  {
    title: "Android App Development Hackathon",
    type: "Hackathon",
    organizer: "Android Club India",
    mode: "Offline",
    location: "Noida",
    deadline: new Date("2026-03-09"),
    applyLink: "https://androidclub.in/hackathon",
    description: "Build innovative Android apps using Kotlin and Jetpack.",
    tags: ["android", "kotlin", "mobile"],
    imageURL: "https://images.unsplash.com/photo-1607252654015-5c4d1158a1f8?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Winter Training Internship Program",
    type: "Internship",
    organizer: "TCS iON",
    mode: "Online",
    location: "Remote",
    deadline: new Date("2026-03-25"),
    applyLink: "https://tcsion.com/training",
    description: "Industry-oriented training and internship for final-year students.",
    tags: ["training", "internship", "corporate"],
    imageURL: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Game Development with Unity",
    type: "Workshop",
    organizer: "GameDev Society",
    mode: "Offline",
    location: "Gurgaon",
    deadline: new Date("2026-02-26"),
    applyLink: "https://gamedevsociety.in/unity",
    description: "Create 2D and 3D games using Unity and C#.",
    tags: ["game-dev", "unity", "csharp"],
    imageURL: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=2070&auto=format&fit=crop"
  },
  {
    title: "Photography & Media Fest",
    type: "Fest",
    organizer: "Media Club IPU",
    mode: "Offline",
    location: "GGSIPU Delhi",
    deadline: new Date("2026-03-04"),
    applyLink: "https://ipu.ac.in/mediafest",
    description: "A creative fest focused on photography, videography, and digital media.",
    tags: ["photography", "media", "fest"],
    imageURL: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=2000&auto=format&fit=crop"
  }
];

module.exports = { data: sampleEvents };